import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/src/components/AuthProvider";
import Navbar from "@/src/components/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/src/lib/authOptions";
import { cn } from "@/lib/utils";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Inventory Management",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

  // const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", figtree.variable)}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
            {children}         
        </AuthProvider>  
      </body>
    </html>
  );
}
