"""Fixed cascade setting for product

Revision ID: 02b01a579ad9
Revises: bc6156c37ae2
Create Date: 2026-08-06 16:36:01.524306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b01a579ad9'
down_revision: Union[str, None] = 'bc6156c37ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
