"""changed date in schema

Revision ID: 232ba6eca07e
Revises: 56f7e6a4d925
Create Date: 2026-07-31 18:35:08.375112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232ba6eca07e'
down_revision: Union[str, None] = '56f7e6a4d925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
