"""Add material_request and release, fixed db issue

Revision ID: 4647137248e1
Revises: 85c7ec52eea2
Create Date: 2026-07-31 17:26:01.828071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4647137248e1'
down_revision: Union[str, None] = '85c7ec52eea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_request',
    sa.Column('mrf_id', sa.Integer(), nullable=False),
    sa.Column('requestor_email', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'NOT_APPROVED', name='approvalstatus'), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('release_status', sa.Enum('PENDING', 'APPROVED', 'NOT_APPROVED', name='approvalstatus'), nullable=True),
    sa.Column('released_by', sa.String(length=50), nullable=True),
    sa.Column('mrf_files', sa.String(length=500), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.email'], ),
    sa.ForeignKeyConstraint(['released_by'], ['users.email'], ),
    sa.ForeignKeyConstraint(['requestor_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('mrf_id')
    )
    op.create_index(op.f('ix_material_request_mrf_id'), 'material_request', ['mrf_id'], unique=False)
    op.create_table('release',
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.Column('mrf_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mrf_id'], ['material_request.mrf_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_index(op.f('ix_release_sub_id'), 'release', ['sub_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_sub_id'), table_name='release')
    op.drop_table('release')
    op.drop_index(op.f('ix_material_request_mrf_id'), table_name='material_request')
    op.drop_table('material_request')
    # ### end Alembic commands ###
