"""modified ondelete for release

Revision ID: 4caa37232474
Revises: 0ded67de49c0
Create Date: 2026-08-03 17:49:51.459002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4caa37232474'
down_revision: Union[str, None] = '0ded67de49c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('release_ibfk_2', 'release', type_='foreignkey')
    op.drop_constraint('release_ibfk_1', 'release', type_='foreignkey')
    op.create_foreign_key(None, 'release', 'material_request', ['mrf_id'], ['mrf_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'release', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'release', type_='foreignkey')
    op.drop_constraint(None, 'release', type_='foreignkey')
    op.create_foreign_key('release_ibfk_1', 'release', 'material_request', ['mrf_id'], ['mrf_id'])
    op.create_foreign_key('release_ibfk_2', 'release', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
