"""Add default date to material_request

Revision ID: 56f7e6a4d925
Revises: 6caeedbf9622
Create Date: 2026-07-31 18:30:26.810129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f7e6a4d925'
down_revision: Union[str, None] = '6caeedbf9622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
