"""Add stock column to products

Revision ID: 6caeedbf9622
Revises: afb803fad476
Create Date: 2026-07-31 18:26:49.846931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6caeedbf9622'
down_revision: Union[str, None] = 'afb803fad476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_request', 'release_status',
               existing_type=mysql.ENUM('PENDING', 'APPROVED', 'NOT_APPROVED'),
               type_=sa.Enum('PENDING', 'RELEASED', 'NOT_RELEASED', name='releasestatus'),
               existing_nullable=True)
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    op.alter_column('material_request', 'release_status',
               existing_type=sa.Enum('PENDING', 'RELEASED', 'NOT_RELEASED', name='releasestatus'),
               type_=mysql.ENUM('PENDING', 'APPROVED', 'NOT_APPROVED'),
               existing_nullable=True)
    # ### end Alembic commands ###
