"""Added tables material_request and release

Revision ID: 708d5e15b3ff
Revises: 9b8f0d1a2ee5
Create Date: 2026-07-31 17:05:56.629590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708d5e15b3ff'
down_revision: Union[str, None] = '9b8f0d1a2ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
