"""Removed an unused foreign key again

Revision ID: 94a0165f0a9d
Revises: 0023cbc21710
Create Date: 2026-08-04 18:55:14.281549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a0165f0a9d'
down_revision: Union[str, None] = '0023cbc21710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
