"""added logs and stock table to db

Revision ID: 9e2a6b8c7846
Revises: 232ba6eca07e
Create Date: 2026-08-02 16:16:08.745649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2a6b8c7846'
down_revision: Union[str, None] = '232ba6eca07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wh_email', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('wh_proof', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['wh_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('add_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wh_id', sa.String(length=50), nullable=False),
    sa.Column('wh_logs', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wh_id'], ['users.email'], ),
    sa.ForeignKeyConstraint(['wh_logs'], ['logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_stock_id'), 'add_stock', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_add_stock_id'), table_name='add_stock')
    op.drop_table('add_stock')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
