"""Fresh schema with all relationships

Revision ID: c57f9f11fdac
Revises: 
Create Date: 2026-08-02 17:21:04.124670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57f9f11fdac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('product_image', sa.String(length=255), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SUPERVISOR', 'CUSTODIAN', 'TECHNICIAN', name='roleenum'), nullable=False),
    sa.Column('area', sa.Enum('CAVITE', 'LAGUNA', 'QUEZON', 'RIZAL', name='areaenum'), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wh_email', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('wh_proof', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['wh_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('material_request',
    sa.Column('mrf_id', sa.Integer(), nullable=False),
    sa.Column('requestor_email', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'NOT_APPROVED', name='approvalstatus'), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('release_status', sa.Enum('PENDING', 'RELEASED', 'NOT_RELEASED', name='releasestatus'), nullable=True),
    sa.Column('released_by', sa.String(length=255), nullable=True),
    sa.Column('mrf_files', sa.String(length=500), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.email'], ),
    sa.ForeignKeyConstraint(['released_by'], ['users.email'], ),
    sa.ForeignKeyConstraint(['requestor_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('mrf_id')
    )
    op.create_index(op.f('ix_material_request_mrf_id'), 'material_request', ['mrf_id'], unique=False)
    op.create_table('add_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wh_id', sa.String(length=255), nullable=False),
    sa.Column('wh_logs', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wh_id'], ['users.email'], ),
    sa.ForeignKeyConstraint(['wh_logs'], ['logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_stock_id'), 'add_stock', ['id'], unique=False)
    op.create_table('release',
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.Column('mrf_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mrf_id'], ['material_request.mrf_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_index(op.f('ix_release_sub_id'), 'release', ['sub_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_sub_id'), table_name='release')
    op.drop_table('release')
    op.drop_index(op.f('ix_add_stock_id'), table_name='add_stock')
    op.drop_table('add_stock')
    op.drop_index(op.f('ix_material_request_mrf_id'), table_name='material_request')
    op.drop_table('material_request')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
