"""Added New table: Inventory, modified product and stock models

Revision ID: e74f8f784233
Revises: 4caa37232474
Create Date: 2026-08-04 16:24:33.530097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e74f8f784233'
down_revision: Union[str, None] = '4caa37232474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.Enum('CAVITE', 'LAGUNA', 'QUEZON', 'RIZAL', name='areaenum'), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_inventory_id'), 'products_inventory', ['id'], unique=False)
    op.add_column('add_stock', sa.Column('inventory_id', sa.Integer(), nullable=False))
    op.drop_constraint('add_stock_ibfk_1', 'add_stock', type_='foreignkey')
    op.create_foreign_key(None, 'add_stock', 'products_inventory', ['inventory_id'], ['id'])
    op.drop_column('add_stock', 'product_id')
    op.alter_column('products', 'product_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('products', 'product_image',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('add_stock', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'add_stock', type_='foreignkey')
    op.create_foreign_key('add_stock_ibfk_1', 'add_stock', 'products', ['product_id'], ['id'])
    op.drop_column('add_stock', 'inventory_id')
    op.drop_index(op.f('ix_products_inventory_id'), table_name='products_inventory')
    op.drop_table('products_inventory')
    # ### end Alembic commands ###
